### PR TITLE
Enh: Facebook Page widget

### PR DESCRIPTION
**Pull request by ArchBlood**
This P/R introduces the Facebook Page Plugin along side of the OAuth client, it also includes updates to the License as Meta Platforms, Inc owns Facebook now;

### Changes
- Introduces new settings for a Facebook pages widget and replacement for outdated [Facebook](https://github.com/GreenMeteor/humhub-facebook-module) module.
- Updates License to Meta Platform, Inc.

### CODE REVIEW

**Comment by luke-** [comment]
@ArchBlood Thanks. Can you please add some more info what the Facebook Page Plugin does? Also some screenshots in the PR would be nice. 

Is the Facebook Page related to the Auth?

**Comment by ArchBlood** [comment]
> @ArchBlood Thanks. Can you please add some more info what the Facebook Page Plugin does? Also some screenshots in the PR would be nice.
> 
> Is the Facebook Page related to the Auth?

Technically no, it does not relate to the Auth part of the module, the idea is more along a similar idea of how [Discord Integrations](https://marketplace.humhub.com/module/discord/description) concept was formed, we didn't want to clutter the marketplace with multiple modules when we could just enhance existing ones.

### Screenshot
Screenshot_5

**Comment by luke-** [comment]
@ArchBlood First of all, thanks for the contribution.

I would prefer to use the “Auth Facebook” module purely for authentication purposes.
Couldn't you also add such a Facebook widget via e.g. the Custom Pages or CodeBox module? 

So my question is, is the feature really needed?
I would like to keep the module as lightweight as possible. Primarly for maintenance.

**Comment by ArchBlood** [comment]
> @ArchBlood First of all, thanks for the contribution.
> 
> I would prefer to use the “Auth Facebook” module purely for authentication purposes.
> Couldn't you also add such a Facebook widget via e.g. the Custom Pages or CodeBox module? 
> 
> So my question is, is the feature really needed?
> I would like to keep the module as lightweight as possible. Primarly for maintenance.
> 
> 

That is possible, and very understandable.

**Pull request closed without merging**
